name: CI Katalon Test

on:
  push:
    branches: [ "main", "Login" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: katalonstudio/katalon:8.6.8

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Katalon Studio Tests
        run: |
          # Menghapus -reportFolder agar tidak menyebabkan error "requires an argument"
          katalonc.sh -noSplash -runMode=console -projectPath="./" -browserType="Chrome (headless)" -testSuitePath="Test Suites/Login" -apiKey="${{ secrets.KATALON_API_KEY }}"