name: CI Katalon Test

on:
  push:
    branches: [ "main", "Login" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Display Server
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Execute Katalon Studio Tests
        uses: katalon-studio/katalon-studio-github-action@v2.2
        with:
          version: '8.6.8'
          args: 'xvfb-run -a katalonc -noSplash -runMode=console -projectPath="./" -browserType="Chrome" -testSuitePath="Test Suites/Login" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'