name: CI Katalon Test

# Menentukan kapan tes berjalan (setiap kali push ke main)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    workflow_dispatch: # <-- Tambahkan baris ini untuk memunculkan tombol manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Katalon Studio Tests
        uses: katalon-studio/katalon-studio-github-action@v2.2 # Gunakan v2.2
        with:
          version: '8.6.8' # Tentukan versi manual daripada 'latest'
          args: '-noSplash -browserType="Chrome (headless)" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Login" -apiKey=${{ secrets.KATALON_API_KEY }}'