name: CI Katalon Test

on:
  push:
    branches: [ "main", "Login" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: katalonstudio/katalon:8.6.8 # Menggunakan image stabil yang sudah teruji

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Katalon Studio Tests
        run: |
          # Eksekusi tes dengan parameter yang sudah kita fix sebelumnya
          katalonc.sh -noSplash -runMode=console -projectPath="./" -browserType="Chrome (headless)" -testSuitePath="Test Suites/Login" -apiKey="${{ secrets.KATALON_API_KEY }}"

      - name: Upload Test Reports
        if: always() # Laporan akan tetap diunggah meskipun tes ada yang gagal
        uses: actions/upload-artifact@v4
        with:
          name: Katalon-Test-Report
          path: report/ # Folder default tempat Katalon menyimpan hasil laporan
          retention-days: 7 # Laporan disimpan selama 7 hari untuk menghemat penyimpanan